version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-sre-dev"
s3_bucket = "test-sre-dev"
s3_prefix = "test-sre-dev"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "TemplateName=test-auto-20201030"